### PR TITLE
Add Firecamp

### PR DESCRIPTION
**Pull request by shreya-gr**
[https://github.com/firecamp-dev/firecamp]

Firecamp is added in the testing category. 

Thanks!

### CODE REVIEW

**Review by fmerian — COMMENTED** [review]
hi @shreya-gr 👋 

thanks for your suggestion, neat product. do you have a pricing page already?

**Comment by shreya-gr** [comment]
Hey @fmerian, 

Yes, we do have a pricing page.

**Review by fmerian — CHANGES_REQUESTED** [review]
also, can you update the following:
- [ ] link to [firecamp.dev](https://firecamp.dev) instead
- [ ] sort alphabetically

and as an OSS project, you can add the following tag:
```
![COMPANY](https://img.shields.io/github/contributors-anon/COMPANY/REPO?style=flat-square&logo=github&labelColor=%230D1117&color=%23161B22)
```

thanks!

**Comment by shreya-gr** [comment]
Updated according to suggestion.

**Comment by fmerian** [comment]
thanks, @shreya-gr! following up on [this comment](https://github.com/agamm/awesome-developer-first/pull/109#issuecomment-1697074454), can you please share a direct link to your public pricing page?

**Review by fmerian — COMMENTED** [review]
thanks, @shreya-gr! following up on [this comment](https://github.com/agamm/awesome-developer-first/pull/109#issuecomment-1697074454), can you please share a direct link to your public pricing page?

**Comment by shreya-gr** [comment]
Hey @fmerian yes here it is - https://firecamp.io/pricing

**Review by fmerian — CHANGES_REQUESTED** [review]
> Hey @fmerian yes here it is - https://firecamp.io/pricing

oh! when reviewing, I visited [firecamp.dev](https://firecamp.dev), not [firecamp.io](https://firecamp.io). my bad!

can you please update the link to `https://firecamp.io/` instead and I'll merge it. thanks so much, @shreya-gr!

**Comment by BernardoSM** [comment]
@fmerian I've been using https://hoppscotch.io/ as Postman alternative and it's very good. Maybe is an opportunity to add there too :)

**Comment by fmerian** [comment]
> @fmerian I've been using https://hoppscotch.io/ as Postman alternative and it's very good. Maybe is an opportunity to add there too :)

thanks for the suggestion, @BernardoSM! please create a PR -- happy to review it.

**Comment by fmerian** [comment]
any update from [last week](https://github.com/agamm/awesome-developer-first/pull/109#pullrequestreview-1606667572), @shreya-gr? thanks!

**Comment by shreya-gr** [comment]
Hey @fmerian link updated. Thanks.

**Review by fmerian — APPROVED** [review]
thanks!

**Pull request merged**
