### PR TITLE
Adding zylitics.io to 'Testing' category

### PR DESCRIPTION
**Pull request by praveen4463**
I am the founder of Zylitics and wanted to add it to Testing category. Please look into it and merge if you think it follows all the requirements.

### CODE REVIEW

**Comment by agamm** [comment]
Can you please list competitors and why this is better?
Reference:
https://github.com/agamm/awesome-developer-first/blob/main/CONTRIBUTING.md
> If you are not adding the only palyer in the category, please post the other competitors and explain why this product is the most awesome from the bunch.

**Comment by praveen4463** [comment]
Yeah sure.
https://www.katalon.com/web-testing/

- Zylitics and Katalon both use selenium under the hood
- Katalon uses local computer resources. The machine running tests needs to have required browsers where tests need to run but Zylitics uses cloud infra to run tests.
- To run tests on multiple OS/browsers, services such as browserstack or saucelabs needs to be used whereas Zylitics has built-in infra.
- Can't run two local instances of browsers at the same time (to run tests in parallel) with Katalon whereas Zylitics can run unlimited parallel builds.
- Zylitics testing apis are easier to use and focused on less experienced users. It uses a DSL that is suitable for users with less programming language. Katalon uses standard java.

**Comment by agamm** [comment]
Thanks for the reply.
It seems also related to https://www.testim.io/ and https://applitools.com/ <- this is the most important to address.

Now regarding Katalon, I skimmed the docs but they do seem to have some of the differentiators you said.
- It seems like they do have cloud runners: https://www.katalon.com/testops/ 
- They also seem to support other browsers: https://docs.katalon.com/katalon-studio/docs/headless-browsers-execution.html#execute-using-console-mode-execution
- Parallel https://docs.katalon.com/katalon-studio/videos/parallel_test_execution_in_katalon_studio.html

**Comment by praveen4463** [comment]
1. _It seems like they do have cloud runners_: That's the ability to integrate own test cluster. Zylitics has test infrastructure built-in. It doesn't provide ability to integrate own infrastructure however ability to integrate pipeline is yet to be added into Zylitics.
2. _They also seem to support other browsers_: I think that are the browsers installed in the machine where katalon is running. They'd surely support them but I meant with Zylitics, browsers need not be installed on a machine that runs test. Zylitics can be run on an iPad too and users can still test on IE.
3. _ Parallel_: Yeah seems so but the good thing about Zylitics is parallel tests are run on separate machines so that screenshots/video of tests can be captured fluently which helps in debugging. With catalon because one of the browser will always run in the background capturing a video wouldn't be possible.

**Comment by praveen4463** [comment]
testim is different because that is record-replay type tool which Zylitics is not. Applitools is different too, it's basically for visual testing.

**Comment by agamm** [comment]
I still think that you are competing with testim.io and applitools, the main difference is that you create tests with code and they use the UI to generate the test suites. Which is neat :+1:
I do think that your site still needs some polishing before it is added, DM me via tw I'll explain.

**Comment by praveen4463** [comment]
I thought you're maintaining a list of useful dev tools. I didn't know Zylitics has to be better than the competition to be listed. There are pros and cons of one thing over the other. For some people a no config tools is better and for some flexibility is important. So it depends.
I know a lot of improvement points about the site and they're in queue to be implemented. I'm closing this PR for now until I do those myself.
Thanks for your time.

**Pull request closed without merging**
