### PR TITLE
Add YepCode

### PR DESCRIPTION
**Pull request by marcos-muino-garcia**
https://yepcode.io/

## checklist

Please make sure you've complied with the [contribution guidelines](https://github.com/agamm/awesome-developer-first/blob/main/CONTRIBUTING.md):
- [x] The homepage clearly states that the product is for developers.
  > "Headless", "API-First", "SaaS" are frequently used keywords.
  > Usually this means that the front page has some code examples :)
- [x] The product is available now and requires payment.
- [x] The PR has a descriptive title -- e.g., `Add {Product}`, not `Update README.md`.
- [x] The new submission isn't a duplicate.
- [x] The entry has a description, is sorted alphabetically, and ends with a full stop.

Thanks!

### CODE REVIEW

**Review by fmerian — CHANGES_REQUESTED** [review]
great suggestion, @marcos-muino-garcia!

could the [Integrations](https://github.com/agamm/awesome-developer-first?tab=readme-ov-file#integrations) section be more accurate?
also, please add a full stop at the end of the description.

thanks!

**Comment by marcos-muino-garcia** [comment]
> great suggestion, @marcos-muino-garcia!
> 
> could the [Integrations](https://github.com/agamm/awesome-developer-first?tab=readme-ov-file#integrations) section be more accurate? also, please add a full stop at the end of the description.
> 
> thanks!

Moved to #integrations. 

I had doubts if it could fit in integrations, automations, or other sections, because we also provide forms (https://yepcode.io/features/forms) and landings (https://yepcode.io/features/forms).

**Comment by fmerian** [comment]
Integrations or Automation — up to you! however, we limit the Misc section to the minimum. otherwise, looks good to me!

what'd be the most relevant section between those two from your perspective?

**Comment by marcos-muino-garcia** [comment]
> Integrations or Automation — up to you! however, we limit the Misc section to the minimum. otherwise, looks good to me!
> 
> what'd be the most relevant section between those two from your perspective?

Integrations LGTM

**Review by fmerian — APPROVED** [review]

**Comment by fmerian** [comment]
welcome to the list!

**Pull request merged**
