### PR TITLE
Add Volta

### PR DESCRIPTION
**Pull request by fmerian**
https://volta.net/

### CODE REVIEW

**Comment by fmerian** [comment]
wdyt @agamm?

**Review by agamm — APPROVED** [review]
LGTM! Thanks

**Review by agamm — CHANGES_REQUESTED** [review]
Just fix the Alphabetic sort.

**Comment by fmerian** [comment]
> Just fix the Alphabetic sort.

absolutely!

**Comment by fmerian** [comment]
ping @atinux for the record

**Pull request merged**
