### PR TITLE
Add Docutain SDK

### PR DESCRIPTION
**Pull request by MarvinFrankenfeld**
https://sdk.docutain.com

### CODE REVIEW

**Comment by fmerian** [comment]
Thanks for the PR, @MarvinFrankenfeld!

It doesn't seem like it has any pricing or paid route on the main page tho ([we're looking for products](https://github.com/agamm/awesome-developer-first/blob/main/CONTRIBUTING.md)).

**Review by fmerian — COMMENTED** [review]
Thanks for the PR, @MarvinFrankenfeld!

It doesn't seem like it has any pricing or paid route on the main page tho ([we're looking for products](https://github.com/agamm/awesome-developer-first/blob/main/CONTRIBUTING.md)).

**Comment by MarvinFrankenfeld** [comment]
There is no fixed pricing, the pricing is individual for each customer, same as for example the Scanbot SDK which is already on your list.

**Comment by fmerian** [comment]
wdyt @agamm?

**Comment by agamm** [comment]
@fmerian I don't like products that don't have available pricing, it doesn't count as developer-friendly in my book. 
Let's also look into Scanbot (we might need to remove it too).

We do appreciate the PR, but we might need to change the contribution criteria to be more specific on this topic.

**Comment by fmerian** [comment]
thanks, @agamm. closing this PR for now. will look into Scanbot.

**Pull request closed without merging**
