### PR TITLE
Added Codename One

### PR DESCRIPTION
**Pull request by shai-almog**
This isn't headless but is clearly a developer first tool. I'm not sure if this is something that's OK. If not feel free to close the PR (sorry in advance).

### CODE REVIEW

**Comment by agamm** [comment]
Seems like a competitor to Flutter and React native, no?
I would open a new category for it maybe, although it seems more like a toolkit and not a product, am I mistaken?

**Comment by shai-almog** [comment]
It's a toolkit with products on top such as cloud build services etc. I can add the others too if that makes sense but they don't have these services.

**Comment by agamm** [comment]
It seems that the service is the hosting (that is the product people are paying for). More like firebase and amplify?

**Comment by shai-almog** [comment]
No. It's a build service more like CI tools. Essentially it removes the need to own a Mac to build an iOS app or a Windows machine to build a Windows app

**Comment by agamm** [comment]
Sorry, so more like:
https://codemagic.io
https://appcircle.io/
https://www.bitrise.io/
?

**Comment by shai-almog** [comment]
Not exactly. Analogy isn't exact since those are CI/CD solutions not a tool that's part of the development process.

**Comment by agamm** [comment]
It is hard for me to categorize it. I'm closing for now. If there will be a big interest I'll re-open and check agian.
Thanks anyways for the submission!

**Pull request closed without merging**
