### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by NathanTarbert**
Added BoxyHQ audit logs product to "Monitoring"

### CODE REVIEW

**Comment by fmerian** [comment]
Is this a duplicate of #62? What would be the best category for BoxyHQ -- `Monitoring` or `Authentication & Identity`?

**Comment by NathanTarbert** [comment]
Hi, Authentication & Identity

**Comment by NathanTarbert** [comment]
We also fit at Monitoring with Audit Logs

**Comment by NathanTarbert** [comment]
Is it ok to be in both sections?

**Comment by fmerian** [comment]
> Is it ok to be in both sections?

some products may be added to multiple sections (Vercel in `CI/CD`, Gitpod and Sonar in `IDE`...). For clarity and fairness, I'd go for one product in one category only.

**Comment by NathanTarbert** [comment]
Ok no problem, thank you

**Comment by agamm** [comment]
I agree with @fmerian 👍

**Pull request closed without merging**
