### PR TITLE
Add Revert

### PR DESCRIPTION
**Pull request by jatinsandilya**
**Website**: https://revert.dev
**Pricing page:**  https://revert.dev/#Pricing

## checklist

Please make sure you've complied with the [contribution guidelines](https://github.com/agamm/awesome-developer-first/blob/main/CONTRIBUTING.md):
- [x] The homepage clearly states that the product is for developers.
  > "Headless", "API-First", "SaaS" are frequently used keywords.
  > Usually this means that the front page has some code examples :)
- [x] The product is available now and requires payment.
- [x] The PR has a descriptive title -- e.g., `Add {Product}`, not `Update README.md`.
- [x] The new submission isn't a duplicate.
- [x] The entry has a description, is sorted alphabetically, and ends with a full stop.

Thanks!

### CODE REVIEW

**Comment by agamm** [comment]
Isn't it only for CMS integrations?

**Comment by jatinsandilya** [comment]
@agamm We're adding other integrations too & will be updating our landing page very soon. You can check our roadmap here: https://github.com/revertinc/revert/issues

**Review by fmerian — COMMENTED** [review]
LGTM. made a minor edit for consistency. thoughts @agamm?

**Review by agamm — APPROVED** [review]
LGTM.

**Pull request merged**
