### PR TITLE
Add Meilisearch

### PR DESCRIPTION
**Pull request by fmerian**
https://www.meilisearch.com/

### CODE REVIEW

**Comment by agamm** [comment]
It's based on elastic, no?

**Comment by fmerian** [comment]
> It's based on elastic, no?

it's different. Elastic (Java) is designed as a backend search engine. Meilisearch (Rust) is for front-facing search.

source: https://docs.meilisearch.com/learn/what_is_meilisearch/comparison_to_alternatives.html#meilisearch-vs-elasticsearch

**Comment by fmerian** [comment]
thanks for clarification, @Strift! thoughts @agamm?

**Comment by agamm** [comment]
> thanks for clarification, @Strift! thoughts @agamm?

Sounds good, even wrote about it on unzip: https://unzip.dev/0x002-search-as-a-service/.

**Pull request merged**
