### PR TITLE
Proposing a new category for developer-focused data exploration tools

### PR DESCRIPTION
**Pull request by eatonphil**
Hey! Nice project! I build [DataStation](https://github.com/multiprocessio/datastation) and it would be neat to have a section for tools like it. I also shared some of the other major open-source/developer-focused tools in the category like Metabase, Redash, and Apache Superset. Cheers!

### CODE REVIEW

**Review by agamm — CHANGES_REQUESTED** [review]
Hi! 
Amazing! Thanks for contributing!
1. Can you please provide an italic category description below the Data Exploration header?
2. Make sure every link have a pricing plan so it is a product and not a tool.
Reference: https://github.com/agamm/awesome-developer-first/blob/main/CONTRIBUTING.md

I changed some files for now :)

**Comment by eatonphil** [comment]
OK! Sounds like this isn't what you're looking for.

**Comment by agamm** [comment]
> OK! Sounds like this isn't what you're looking for.

@eatonphil ON the contrary, it seems like Metabase, DataStation and Redash hosted are a great fit and also the category.
You just need to fix the changes I suggested.

**Comment by agamm** [comment]
> > OK! Sounds like this isn't what you're looking for.
> 
> @eatonphil ON the contrary, it seems like Metabase, DataStation and Redash hosted are a great fit and also the category. You just need to fix the changes I suggested.

I'd be happy to merge if you fix them and restore the branch :+1:

**Pull request closed without merging**
