### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by MicheleTiledesk**
Add Chatbot Design Studio by Tiledesk.
Mix AI (based on Bert machine learning model) with proactive rules for customer engagement through a no-code chatbot builder.

### CODE REVIEW

**Comment by agamm** [comment]
Hi @MicheleTiledesk , it seems like it doesn't work with our [contributing](https://github.com/agamm/awesome-developer-first/blob/main/CONTRIBUTING.md) guidelines (not developer-first,  more "no-code" oriented).

**Comment by MicheleTiledesk** [comment]
Hi @agamm thank you for the reply. It's true that the new version of the tool has a no-code builder. We have also many extension points, APIs event-driven, webhooks, etc. 
More information are available in our [developer zone](https://developer.tiledesk.com/) and on our [GitHub organization](https://github.com/Tiledesk)

**Comment by agamm** [comment]
> Hi @agamm thank you for the reply. It's true that the new version of the tool has a no-code builder. We have also many extension points, APIs event-driven, webhooks, etc. More information are available in our [developer zone](https://developer.tiledesk.com/) and on our [GitHub organization](https://github.com/Tiledesk)

Still, the repo is specifically for developer-first products as stated in the contributing guide. There need to be more references to developers and not no-code builders.
I will have to close for now, but good luck🙏

**Comment by MicheleTiledesk** [comment]
Thank you 😉

Il giorno mer 22 feb 2023 alle ore 15:16 Agam More ***@***.***>
ha scritto:

**Pull request closed without merging**
