### PR TITLE
Add Polybase

### PR DESCRIPTION
**Pull request by shaki150697**
As a Developer Relations Engineer of Polybase, I would love to have Polybase added as a resource to your awesome list! Polybase's star is to ensure the developers do not know if it's a web2 or a web3 product. Polybase APIs are very similar to Firebase, Firestore, or Postgres and there is a zero learning curve for any developer using Polybase. Polybase's mission is to become the single database for the entire humanity!

### CODE REVIEW

**Comment by fmerian** [comment]
thanks for the suggestion, @shaki150697!

putting on hold for now until it becomes a product -- we’re looking for products, eg tools/services that people pay for, as stated in the [guidelines](https://github.com/agamm/awesome-developer-first/blob/main/CONTRIBUTING.md).

also, please sort alphabetically. oh and I renamed the PR for consistency.

**Review by fmerian — CHANGES_REQUESTED** [review]
Sort alphabetically

**Comment by agamm** [comment]
@shaki150697 ?

**Comment by fmerian** [comment]
closing for now until there's a response

**Pull request closed without merging**
