### PR TITLE
Update Vercel description

### PR DESCRIPTION
**Pull request by eric-hc**

### CODE REVIEW

**Comment by agamm** [comment]
Why is this description better? This sounds a bit too salesy...

**Comment by eric-hc** [comment]
It is on their website, so it might sound sale-sy, but it is more accurate. 

>Deploy JAMStack (mainly Next.js) via CLI

This also just isn't true and encompassing of everything Vercel does.

**Comment by agamm** [comment]
> It is on their website, so it might sound sale-sy, but it is more accurate.
> 
> > Deploy JAMStack (mainly Next.js) via CLI
> 
> This also just isn't true and encompassing of everything Vercel does.

What about something like:
> cloud platform for building and deploying serverless web applications, static websites, and Jamstack projects.

**Comment by agamm** [comment]
@fmerian WDYT?

**Comment by fmerian** [comment]
> > cloud platform for building and deploying serverless web applications, static websites, and Jamstack projects.

> @fmerian WDYT?

less salesy, more accurate. right balance imho 👍

**Pull request merged**
