### PR TITLE
Add Tianji

### PR DESCRIPTION
**Pull request by moonrailgun**
[Insert URL to the product here.]

https://tianji.msgbyte.com/

## checklist

Please make sure you've complied with the [contribution guidelines](https://github.com/agamm/awesome-developer-first/blob/main/CONTRIBUTING.md):
- [x] The homepage clearly states that the product is for developers.
  > "Headless", "API-First", "SaaS" are frequently used keywords.
  > Usually this means that the front page has some code examples :)
- [ ] The product is available now and requires payment.
- [x] The PR has a descriptive title -- e.g., `Add {Product}`, not `Update README.md`.
- [x] The new submission isn't a duplicate.
- [x] The entry has a description, is sorted alphabetically, and ends with a full stop.

Thanks!

### CODE REVIEW

**Review by fmerian — CHANGES_REQUESTED** [review]
neat product -- thanks for the suggestion, @moonrailgun!

however, I don't see any pricing plans. did I miss something?

**Comment by moonrailgun** [comment]
Oh sorry, its a open source project. its must be allow `requires payment` project? 

*I misread it as `available now or requires payment`*

**Comment by fmerian** [comment]
> Oh sorry, its a open source project. its must be allow `requires payment` project?

yes, this list focuses on products that require payments. sorry.

here are some awesome lists for OSS projects:
* [awesome-foss-apps](https://github.com/DataDaoDe/awesome-foss-apps)
* [awesome-oss](https://github.com/sereneblue/awesome-oss)
* [awesome-oss-alternatives](https://github.com/RunaCapital/awesome-oss-alternatives)
* [awesome-oss-saas](https://github.com/vihar/awesome-oss-saas)
* [foss-for-dev](https://github.com/tvvocold/FOSS-for-Dev)
* [find-oss](https://github.com/SimoMay/find-oss)
* [free-for-dev](https://github.com/ripienaar/free-for-dev)
* [learn-from-open-source](https://github.com/elie222/learn-from-open-source)

FYI I found them in [this repo](https://github.com/fmerian/awesome-developer-first-channels). hope it helps! keep up your great work

**Comment by moonrailgun** [comment]
sure, i will back later(after start business plan)  😄

**Comment by fmerian** [comment]
> sure, i will back later(after start business plan) 😄

please do! looking forward to it!

**Pull request closed without merging**
