### PR TITLE
Add APITemplate.io and CraftMyPDF to Media

### PR DESCRIPTION
**Pull request by bktan81**

### CODE REVIEW

**Comment by agamm** [comment]
Hi, thanks for the contribution!
1. Can you please add `APITemplate.io` at the bottom of the section so it it will be ordered?
2. I don't think that `CraftMyPDF` applies to this list, it is more of a GUI drag and drop tool and I wouldn't say that it is a developer oriented product in that sense.

After the changes we can merge :+1:

**Review by agamm — CHANGES_REQUESTED** [review]
Hi, thanks for the contribution!

- Can you please add `APITemplate.io` at the bottom of the section so it it will be ordered?
- I don't think that `CraftMyPDF` applies to this list, it is more of a GUI drag and drop tool and I wouldn't say that it is a developer oriented product in that sense.

After the changes we can merge 👍

**Comment by bktan81** [comment]
Hi Agam,

Thanks for the suggestions!

- `APITemplate.io` has been moved to the bottom of the link(Initially I thought that it was ordered in alphabetical order)
- `CraftMyPDF` is an API product, we offer PDF generation API. The drag-and-drop is for designers/developers to create PDF templates easily, but the core feature is still the API for PDF generation. Additionally, we also offer a white-label PDF template editor which will reduce the development costs.

Thanks again!

**Comment by agamm** [comment]
Hi @bktan81 ,

1. Yeah, I want to order it by date, so older ones are on top.
2. I still think CraftMyPDF isn't supposed to be here. When I see the product it has a major part which is drag and drop => non developers can be the main users -> and then it can be sent to the developers to integrate, and the integration part isn't the main product.
I have to filter out products in some way, because most software today will have some aspect of integration, but that doesn't mean it is a developer-first product :)

Note: I just clarified the [CONTRIBUTING.md](https://github.com/agamm/awesome-developer-first/blob/main/CONTRIBUTING.md)
I see that your product does have some competitors, what makes it better than them, so we could continue the quality of this repo?
- https://www.useanvil.com/products/pdf-filling-api/
- https://pdfgeneratorapi.com/

**Comment by agamm** [comment]
Note I added the reports generation section, which could be more relevant.

**Comment by bktan81** [comment]
The idea of CraftMyPDF was from some of my existing customers(APITemplate.io), APITemplate.io is for HTML to PDF conversion. Some of my customers wanted to design templates easily without learning HTML, so I created a drag-and-drop editor.  

I understand where you are coming from: both of the products you mentioned are great products, but they are other similar products in the market too.

**Comment by bktan81** [comment]
Hi @agamm I removed CraftMyPDF :)

**Comment by agamm** [comment]
I checked the competition and they didn't seem to have better similarweb stats, merging! 🎉

**Pull request merged**
