### PR TITLE
Add Lago

### PR DESCRIPTION
**Pull request by fmerian**
Lago offers a self-hosted, scalable and modular architecture for metering and usage-based billing.

### CODE REVIEW

**Review by agamm — CHANGES_REQUESTED** [review]
Just saw them! Thanks for the PR :)

Note, I'm putting this on hold until it becomes a product - we don't allow free tools (we are looking for products).

**Comment by fmerian** [comment]
Thanks, @agamm :) 

I cc the maker @sarkissianraffi for the record

**Comment by sarkissianraffi** [comment]
Hi @agamm, Lago is a product! :) 
Having an open-core version for free does not mean the entire product is free. We have self-hosted premium licences and a cloud-hosted (paying) version of Lago. Happy to give more info if needed

**Comment by agamm** [comment]
@sarkissianraffi Sorry my bad! it just doesn't seem like it has any pricing or paid-route on the main landing page. And yeah I know about open-core and the rest ([I even wrote about it](https://unzip.dev/0x00d-open-source-business-models/)). Supabase has a very clear pricing page and a way to pay for the product. I'd love to add Lago but I need a better indication on the site that it isn't just an Open-source tool. Do you have an ETA for when it will be more indicative, or am I missing something big time on the landing page?

**Comment by agamm** [comment]
Closing until there is a response.

**Comment by agamm** [comment]
> @agamm thoughts about [this pricing page](https://getlago.com/pricing)?

It's better now, but I really don't like those "contact us" pages. I feel like we might want to add a new rule of concrete pricing, developers hate unknown pricing.

**Pull request closed without merging**
